- name: Prepare system for Kubernetes
  hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 1800

    - name: Install base packages
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - apt-transport-https
          - conntrack
          - socat
          - ebtables
          - ipset
          - lsof
          - jq
          - python3-pip
        state: present


    - name: Ensure kernel modules for Kubernetes
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules
      shell: |
        modprobe overlay || true
        modprobe br_netfilter || true

    - name: Configure sysctl for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl params
      command: sysctl --system | cat