---
- name: Prepare Worker Nodes
  hosts: execute_nodes
  become: yes
  tasks:
    - name: Install kubeadm, kubelet, kubectl
      package:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
      when: ansible_os_family == "RedHat"
        
    - name: Create test file
      copy:
        content: "Worker node prepared: {{ inventory_hostname }}"
        dest: /tmp/worker_prepared.txt
        mode: '0644'

