- name: Deploy containerd configure script
  template:
    src: templates/configure_containerd.sh.j2
    dest: /usr/local/sbin/mas-configure-containerd.sh
    mode: "0755"
    newline_sequence: "\n"

- name: Run containerd configure script
  shell: |
    sed -i 's/\r$//' /usr/local/sbin/mas-configure-containerd.sh
    /bin/bash /usr/local/sbin/mas-configure-containerd.sh
  args:
    executable: /bin/bash
